### PR TITLE
fix(rdsinstance): Updates will now set ResourceCredentialsSecretUserKey in ConnectionDetails if masterUsername is set

### LINKED ISSUE #1999: RDSInstance doesn't set username in `writeConnectionSecretToRef` if you are importing an existing resource
### What happened?
If I import an existing RDSInstance that has been orphaned, the username in the `writeConnectionSecret` is never set because its only ever set in the `create` workflow.

### How can we reproduce it?
Create an RDSInstance using 
```
deletionPolicy: Orphan
writeConnectionSecretToRef:
  name: foobar
  namespace: foobar1
forProvider:
...
   masterUsername: foo
   masterPasswordSecretRef:
     key: pass
     name: secret
     namespace: secret
...    
connectionDetails:
    - fromConnectionSecretKey: endpoint
    - fromConnectionSecretKey: port
    - fromConnectionSecretKey: username
    - fromConnectionSecretKey: password
```

Delete the Secret/manifests

### What environment did it happen in?
Crossplane version: 
V0.46.0

### PR DESCRIPTION
**Pull request by trystanleftwich**
### Description of your changes

in rdsInstance when running an update always set `ResourceCredentialsSecretUserKey` in the ConnectionDetails if masterUsername exists.

Fixes #1999

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Created an RDSInstance, Deleted it when deletionPolicy = Orphan.
Re-added the RDSInstance, checked the secret contained `username`

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: pkg/controller/database/rdsinstance/rdsinstance.go [hunk 1]
```diff
@@ -277,12 +277,18 @@ func (e *external) Update(ctx context.Context, mg resource.Managed) (managed.Ext
...
 	}
 
+	if cr.Spec.ForProvider.MasterUsername != nil {
+		if conn != nil {
+			conn[xpv1.ResourceCredentialsSecretUserKey] = []byte(aws.ToString(cr.Spec.ForProvider.MasterUsername))
+		} else {
+			conn = managed.ConnectionDetails{xpv1.ResourceCredentialsSecretUserKey: []byte(aws.ToString(cr.Spec.ForProvider.MasterUsername))}
+		}
+	}
+
```
Comment (MisterMX) [inline pkg/controller/database/rdsinstance/rdsinstance.go:291]: I think that can be simplied:

```suggestion
	conn := managed.ConnectionDetails{}
	
	if changed {
		conn[xpv1.ResourceCredentialsSecretPasswordKey] = []byte(pwd)
	}

	if cr.Spec.ForProvider.MasterUsername != nil {
		conn[xpv1.ResourceCredentialsSecretUserKey] = []byte(aws.ToString(cr.Spec.ForProvider.MasterUsername))
	}

```

**Review by MisterMX — CHANGES_REQUESTED** [review]

**Comment by MisterMX** [comment]
@trystanleftwich can you rebase on the latest master to fix e2e tests?

File: pkg/controller/database/rdsinstance/rdsinstance.go (hunk 1 above)
Comment (trystanleftwich) [reply pkg/controller/database/rdsinstance/rdsinstance.go]: Updated, the only reason I didn't do this originally is because I wasn't sure if `managed.ConnectionDetails{}` needed to be `nil` not `empty`.
But then while implementing it I realised it should never be empty because `Spec.ForProvider.MasterUsername` should always be set.
Thanks!

**Comment by trystanleftwich** [comment]
> @trystanleftwich can you rebase on the latest master to fix e2e tests?

@MisterMX I rebased but it didn't run the full suite it seems. Anyway to trigger a run?

**Comment by MisterMX** [comment]
@trystanleftwich can you try squashing your changes into a single commit?

**Review by MisterMX — APPROVED** [review]
LGTM. Thank you very much @trystanleftwich!
