### PR TITLE
fix(efs): Adjusted Filesystem Update

### LINKED ISSUE #2135: EFS FileSystem not updated
### What happened?

I create a FileSystem MR among other MR from a XR. The creation of all MRs succeed, and my XR is "Ready" and "Synced" (as well as the FileSystem).
When I update the parameters of my XR (FileSystem throughputMode, or FileSystem backup), my XR is ready (also the FileSystem MR) with updated parameter values but the external resource EFS FileSystem stays unchanged : throughputMode or/and backup parameters are not updated.
The FileSystem MR Status values are regularly well updated.
The external resource EFS FileSystem and its dependencies are well deleted when I delete my XR.

### How can we reproduce it?
Spec of the EFS FileSystem:
```bash
...
Spec:
  Deletion Policy:  Delete
  For Provider:
    Backup:            false
    Encrypted:         true
    Performance Mode:  generalPurpose
    Region:            eu-west-3
    Tags:
      Key:            Name
      Value:          default-testfab
    Throughput Mode:  bursting
  Management Policies:
    *
  Provider Config Ref:
    Name:  aws-provider
...
```

### What environment did it happen in?
Crossplane version: 1.17.1
crossplane-contrib/provider-aws: 0.50.6 (and 0.44.1 on other cluster)

### PR DESCRIPTION
**Pull request by kuseler**
### Description of your changes

Fixes #2135

This change enables the update of Throughputmode and BackupPolicy. 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

1. apply efs1.yml:

```yaml
kind: FileSystem
metadata:
  name: greattestingfilesystem
spec:
  deletionPolicy:  Delete
  forProvider:
    backup:            false
    encrypted:         false
    performanceMode:  generalPurpose
    region:            eu-west-3
    throughputMode:  elastic
  providerConfigRef:
    name: aws-community-provider
```

2. apply efs2.yml

```yaml
apiVersion: efs.aws.crossplane.io/v1alpha1
kind: FileSystem
metadata:
  name: greattestingfilesystem
spec:
  deletionPolicy:  Delete
  forProvider:
    backup:            true
    encrypted:         true
    performanceMode:  generalPurpose
    region:            eu-west-3
    throughputMode:  bursting
  providerConfigRef:
    name: aws-community-provider
```

3. confirm that the throughputmode and BackupPolicy have changed.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: pkg/controller/efs/filesystem/setup.go [hunk 1]
```diff
@@ -67,11 +74,54 @@ func SetupFileSystem(mgr ctrl.Manager, o controller.Options) error {
...
 		}
+		if !ptr.Equal(cr.Spec.ForProvider.ThroughputMode, res.ThroughputMode) {
+			return false, "", nil
+		}
+
+		err := e.cacheBackupPolicyHelper(res.FileSystemId)
+		if err != nil {
+			return false, "", err
+		}
+		if *cr.Spec.ForProvider.Backup != e.cache.backupPolicy {
```
Comment (MisterMX) [inline pkg/controller/efs/filesystem/setup.go:122]: Possible nil deref

File: pkg/controller/efs/filesystem/setup.go [hunk 2]
```diff
@@ -67,11 +74,54 @@ func SetupFileSystem(mgr ctrl.Manager, o controller.Options) error {
...
 		if pointer.Int64Value(cr.Spec.ForProvider.ProvisionedThroughputInMibps) != int64(aws.Float64Value(res.ProvisionedThroughputInMibps)) {
 			return false, "", nil
 		}
+		if !ptr.Equal(cr.Spec.ForProvider.ThroughputMode, res.ThroughputMode) {
+			return false, "", nil
+		}
+
+		err := e.cacheBackupPolicyHelper(res.FileSystemId)
+		if err != nil {
+			return false, "", err
```
Comment (MisterMX) [inline pkg/controller/efs/filesystem/setup.go:120]: We should always `errors.Wrap` with a custom message to easily identify where the error comes from.

File: pkg/controller/efs/filesystem/setup.go [hunk 3]
```diff
@@ -67,11 +74,54 @@ func SetupFileSystem(mgr ctrl.Manager, o controller.Options) error {
...
+	if err != nil {
+		var awsErr awserr.Error
+		if errors.As(err, &awsErr) && awsErr.Code() == "PolicyNotFound" {
+			e.cache.backupPolicy = false
+			return nil
+		}
+		return err
+	}
+
+	switch *policy.BackupPolicy.Status {
```
Comment (MisterMX) [inline pkg/controller/efs/filesystem/setup.go:100]: Possible nil deref

File: pkg/controller/efs/filesystem/setup.go [hunk 4]
```diff
@@ -67,11 +74,54 @@ func SetupFileSystem(mgr ctrl.Manager, o controller.Options) error {
...
+	// Get BackupPolicy
+	//default is no backup
+	policy, err := e.client.DescribeBackupPolicy(&svcsdk.DescribeBackupPolicyInput{FileSystemId: filesystemId})
+	if err != nil {
+		var awsErr awserr.Error
+		if errors.As(err, &awsErr) && awsErr.Code() == "PolicyNotFound" {
+			e.cache.backupPolicy = false
+			return nil
+		}
+		return err
```
Comment (MisterMX) [inline pkg/controller/efs/filesystem/setup.go:97]: Should be moved into an extra function like here: https://github.com/crossplane-contrib/provider-aws/blob/master/pkg/controller/eks/addon/zz_conversions.go#L226

```suggestion
		return resource.Ignore(err, IsNotFound())
```

File: pkg/controller/efs/filesystem/setup.go [hunk 5]
```diff
@@ -96,12 +146,41 @@ func postObserve(_ context.Context, cr *svcapitypes.FileSystem, obj *svcsdk.Desc
...
+
+		if pointer.StringValue(obj.FileSystemId) == "" {
+			obj.FileSystemId = pointer.ToOrNilIfZeroValue(meta.GetExternalName(cr))
+		}
+		_, err := e.client.PutBackupPolicyWithContext(ctx,
+			&svcsdk.PutBackupPolicyInput{
+				FileSystemId: obj.FileSystemId,
+				BackupPolicy: &svcsdk.BackupPolicy{Status: policy}})
+		if err != nil {
+			return err
```
Comment (MisterMX) [inline pkg/controller/efs/filesystem/setup.go:172]: missing `errors.Wrap`

File: pkg/controller/efs/filesystem/setup.go [hunk 6]
```diff
@@ -96,12 +146,41 @@ func postObserve(_ context.Context, cr *svcapitypes.FileSystem, obj *svcsdk.Desc
...
+			policy = aws.String("DISABLED")
+		}
+
+		if pointer.StringValue(obj.FileSystemId) == "" {
+			obj.FileSystemId = pointer.ToOrNilIfZeroValue(meta.GetExternalName(cr))
+		}
+		_, err := e.client.PutBackupPolicyWithContext(ctx,
+			&svcsdk.PutBackupPolicyInput{
+				FileSystemId: obj.FileSystemId,
+				BackupPolicy: &svcsdk.BackupPolicy{Status: policy}})
```
Comment (MisterMX) [inline pkg/controller/efs/filesystem/setup.go:170]: For consistency the code formatting should be same as everywhere else: Newline before `}`.

File: pkg/controller/efs/filesystem/setup.go [hunk 7]
```diff
@@ -96,12 +146,41 @@ func postObserve(_ context.Context, cr *svcapitypes.FileSystem, obj *svcsdk.Desc
...
-func preUpdate(_ context.Context, cr *svcapitypes.FileSystem, obj *svcsdk.UpdateFileSystemInput) error {
+func (e *custom) preUpdate(ctx context.Context, cr *svcapitypes.FileSystem, obj *svcsdk.UpdateFileSystemInput) error {
 	obj.FileSystemId = pointer.ToOrNilIfZeroValue(meta.GetExternalName(cr))
 	// Type of this field is *float64 but in practice, only integer values are allowed.
 	if cr.Spec.ForProvider.ProvisionedThroughputInMibps != nil {
 		obj.ProvisionedThroughputInMibps = aws.Float64(float64(pointer.Int64Value(cr.Spec.ForProvider.ProvisionedThroughputInMibps)))
 	}
+
+	if e.cache.backupPolicy != *cr.Spec.ForProvider.Backup {
+		var policy *string
```
Comment (MisterMX) [inline pkg/controller/efs/filesystem/setup.go:157]: Don't have to use a pointer here and stick with value. We can reference it with `&` later.

File: pkg/controller/efs/filesystem/setup.go [hunk 8]
```diff
@@ -96,12 +146,41 @@ func postObserve(_ context.Context, cr *svcapitypes.FileSystem, obj *svcsdk.Desc
...
+			return err
+		}
+	}
+
+	/*	Backup is not a direct part of the FileSystem, but an externally managed BackupPolicy.
+		Changing only the backup policy will result in an empty request and thus an Error.
+		To avoid this, we return an error if the BackupPolicy is the only thing that has changed.
+	*/
+	if ptr.Equal(cr.Spec.ForProvider.ThroughputMode, obj.ThroughputMode) && pointer.Int64Value(cr.Spec.ForProvider.ProvisionedThroughputInMibps) == int64(aws.Float64Value(obj.ProvisionedThroughputInMibps)) {
+		return errors.New("throughputmode and provisionedthroughputinmibps are unchanged, aborting update")
```
Comment (MisterMX) [inline pkg/controller/efs/filesystem/setup.go:181]: Returning an error here will trigger a constant reschedule of the reconcile and make the resource show as unready - although there is actual not any error. If we really would want to prevent the update we would need to modify the `IsResourceUpToDate` result in `Observe`.

**Review by MisterMX — CHANGES_REQUESTED** [review]

File: pkg/controller/efs/filesystem/setup.go [hunk 9]
```diff
@@ -67,11 +73,25 @@ func SetupFileSystem(mgr ctrl.Manager, o controller.Options) error {
 		Complete(r)
 }
 
+type custom struct {
+	kube     client.Client
+	client   svcsdkapi.EFSAPI
+	external *external
+
+	cache struct {
+		backupPolicy bool
```
Comment (MisterMX) [inline pkg/controller/efs/filesystem/setup.go:82]: Boolean variables should always describe "yos-or-no" states. Better here would be `shouldUpdateBackupPolicy`.

File: pkg/controller/efs/filesystem/setup.go [hunk 10]
```diff
@@ -126,3 +152,60 @@ func postCreate(_ context.Context, cr *svcapitypes.FileSystem, obj *svcsdk.FileS
...
+		e.cache.backupPolicy = true
+	case "DISABLED", "DISABLING":
+		e.cache.backupPolicy = false
+	}
+	return nil
+}
+
+func (e *custom) updateBackupPolicy(ctx context.Context, cr *svcapitypes.FileSystem, obj *svcsdk.DescribeFileSystemsOutput) error {
+	for _, res := range obj.FileSystems {
+		err := e.cacheBackupPolicy(res.FileSystemId)
```
Comment (MisterMX) [inline pkg/controller/efs/filesystem/setup.go:176]: This `cache` thingy is only used as a workaround to pass state information from `Observe` to `Create`, `Update` or `Delete` so you don't have to recompute it, i.e. difference in resource tags - because the controller framwork does not allow passing custom values in a `managed.ExternalObservation`.

File: pkg/controller/efs/filesystem/setup.go [hunk 11]
```diff
@@ -126,3 +152,60 @@ func postCreate(_ context.Context, cr *svcapitypes.FileSystem, obj *svcsdk.FileS
 	meta.SetExternalName(cr, pointer.StringValue(obj.FileSystemId))
 	return managed.ExternalCreation{}, nil
 }
+
+func (e *custom) cacheBackupPolicy(filesystemId *string) error {
```
Comment (MisterMX) [inline pkg/controller/efs/filesystem/setup.go:156]: Rather have a function `isBackupPolicyUpToDate` that returns a `(bool, error)`.

File: pkg/controller/efs/filesystem/setup.go [hunk 12]
```diff
@@ -93,6 +113,12 @@ func postObserve(_ context.Context, cr *svcapitypes.FileSystem, obj *svcsdk.Desc
 	obs.ConnectionDetails = managed.ConnectionDetails{
 		svcapitypes.ResourceCredentialsSecretIDKey: []byte(meta.GetExternalName(cr)),
 	}
+
+	// BackupPolicy is managed separately from the FileSystem, so we update it here to avoid empty requests in preUpdate
+	updateBackupPolicyErr := e.updateBackupPolicy(ctx, cr, obj)
+	if updateBackupPolicyErr != nil {
+		return managed.ExternalObservation{}, updateBackupPolicyErr
+	}
```
Comment (MisterMX) [inline pkg/controller/efs/filesystem/setup.go:121]: I don't have much EFS insights but I think this section should only be executed if `obs.ResourceExists` is true?

File: pkg/controller/efs/filesystem/setup.go [hunk 13]
```diff
@@ -2,9 +2,13 @@ package filesystem
...
+	"github.com/aws/aws-sdk-go/aws/awserr"
+	"github.com/pkg/errors"
+	"k8s.io/utils/ptr"
 
 	"github.com/aws/aws-sdk-go/aws"
 	svcsdk "github.com/aws/aws-sdk-go/service/efs"
+	svcsdkapi "github.com/aws/aws-sdk-go/service/efs/efsiface"
 	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
 	"github.com/crossplane/crossplane-runtime/pkg/connection"
 	"github.com/crossplane/crossplane-runtime/pkg/controller"
```
Comment (MisterMX) [inline pkg/controller/efs/filesystem/setup.go:14]: The linter requires Go imports to be in a specific order (defined in `.golangci-lint.yml`) separated by empty lines:

* Go standard packages
* Third-party packages
* `github.com/crossplane-contrib/provider-aws/*`

**Review by MisterMX — CHANGES_REQUESTED** [review]

**Review by MisterMX — CHANGES_REQUESTED** [review]

**Review by MisterMX — APPROVED** [review]
LGTM. Thank you very much @kuseler!
