### PR TITLE
fix(kafka/cluster): fill connectionDetails with bootstrap brokers

### LINKED ISSUE #1711: MSK: write bootstrap connection strings
When MSK is provisioned, the broker information is written to the desired connection string. To connect to MSK, it's preferred to use the bootstrap TLS and bootstrap Plaintext strings. These strings should be written out as connection information. 

I'm not a kafka expert, but I don't think it's desirable to report back the broker URLs. The bootstrap connections will allow clients to discover them.

### PR DESCRIPTION
**Pull request by wotolom**
### Description of your changes

use an `GetBootstrapBrokers` API call (https://docs.aws.amazon.com/cli/latest/reference/kafka/get-bootstrap-brokers.html) to correctly fill in the different endpoints of the AWS MSKafka Cluster into the `ConnectionDetails`

- add `GetBootstrapBrokers` API call in `postObserve` to insert endpoints into `ConnectionDetails`
- correct some wrongly set variable in `generateClientAuthentication`

Fixes #1711

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
manually

### CODE REVIEW

File: pkg/controller/kafka/cluster/setup.go [hunk 1]
```diff
@@ -121,13 +122,37 @@ func preObserve(_ context.Context, cr *svcapitypes.Cluster, obj *svcsdk.Describe
...
 	switch awsclients.StringValue(obj.ClusterInfo.State) {
 	case string(svcapitypes.ClusterState_ACTIVE):
 		cr.SetConditions(xpv1.Available())
+
+		// see: https://docs.aws.amazon.com/msk/latest/developerguide/msk-get-bootstrap-brokers.html
+		// retrieve cluster bootstrap brokers (endpoints)
+		// not possible in every cluster state (e.g. "You can't get bootstrap broker nodes for a cluster in DELETING state.")
+		endpoints, err := u.client.GetBootstrapBrokersWithContext(ctx, &svcsdk.GetBootstrapBrokersInput{ClusterArn: awsclients.String(meta.GetExternalName(cr))})
+		if err != nil {
+			return obs, awsclients.Wrap(err, errBootstrapBrokers)
```
Comment (MisterMX) [inline pkg/controller/kafka/cluster/setup.go:146]:
```suggestion
			return obs, awsclients.Wrap(err, errGetBootstrapBrokers)
```

**Review by MisterMX — CHANGES_REQUESTED** [review]

File: pkg/controller/kafka/cluster/setup.go (hunk 1 above)
Comment (wotolom) [reply pkg/controller/kafka/cluster/setup.go]: Makes sense. Done.

**Review by MisterMX — APPROVED** [review]
LGTM. Thank you very much @wotolom!
