### PR TITLE
feat(cache): fix version handling for #1617

### LINKED ISSUE #1617: Elasticache cluster: Specific version selection is not allowed for 'x.x.x', please use 'x.x'
### What happened?
When creating Elasticache cluster with engineVersion: "6.2.6" for example , the next error appears - `InvalidParameterValue: Specific version selection is not allowed for '6.2.6', please use '6.2'`

### How can we reproduce it?
Create a new Elasticache cluster with x.x.x enging version

### PR DESCRIPTION
**Pull request by haarchri**
Signed-off-by: Christopher Paul Haar <christopherpaul.haar@dkb.de>

### Description of your changes
changed version handling for cache cluster

Fixes #1617

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
added new example

```
kubectl get managed
NAME                                                          STATUS      READY   SYNCED   AGE
cachecluster.cache.aws.crossplane.io/aws-memcached-standard   available   True    True     19m
cachecluster.cache.aws.crossplane.io/redis-cache-cluster      available   True    True     19m
```

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by ezgidemirel — APPROVED** [review]
thanks for the PR @haarchri! LGTM

File: pkg/clients/elasticache/elasticache.go [hunk 1]
```diff
@@ -677,6 +679,16 @@ func GenerateCreateCacheClusterInput(p cachev1alpha1.CacheClusterParameters, id
...
 	}
 
+	if p.EngineVersion != nil {
+		version, err := getVersion(p.EngineVersion)
+		if err != nil {
+			return nil, err
+		}
+		c.EngineVersion = version
+	} else {
+		c.EngineVersion = p.EngineVersion
```
Comment (nabuskey) [inline pkg/clients/elasticache/elasticache.go:689]: This else clause is not needed if you keep
```
EngineVersion:              p.EngineVersion,
```

File: pkg/clients/elasticache/elasticcachecluster_test.go [hunk 2]
```diff
@@ -158,7 +158,7 @@ func TestGenerateCreateCacheClusterInput(t *testing.T) {
 
 	for name, tc := range cases {
 		t.Run(name, func(t *testing.T) {
-			r := GenerateCreateCacheClusterInput(tc.in, clusterID)
+			r, _ := GenerateCreateCacheClusterInput(tc.in, clusterID)
```
Comment (nabuskey) [inline pkg/clients/elasticache/elasticcachecluster_test.go:161]: I think there should be a test case for specifying a version.

File: pkg/clients/elasticache/elasticache.go [hunk 3]
```diff
@@ -816,5 +840,40 @@ func IsClusterUpToDate(name string, in *cachev1alpha1.CacheClusterParameters, ob
...
+			}
+		}
+		// to ignore in following equal
+		desired.EngineVersion = observed.EngineVersion
+	}
+
 	return cmp.Equal(desired, observed, cmpopts.EquateEmpty(), cmpopts.IgnoreTypes(document.NoSerde{})), nil
 }
+
+func getVersion(version *string) (*string, error) {
```
Comment (nabuskey) [inline pkg/clients/elasticache/elasticache.go:864]: If we want to be sure we are sending a request with a supported version, we could call `DescribeCacheEngineVersions` and store them in a map, then check against it. Might be an overkill though.

Comment (haarchri) [reply pkg/clients/elasticache/elasticache.go:864]: think this is overkill :D

File: pkg/clients/elasticache/elasticache.go (hunk 1 above)
Comment (haarchri) [reply pkg/clients/elasticache/elasticache.go:689]: yes but i think its easier to see that we doing some version stuff with this variable - i think we should leave it as is

**Review by MisterMX — APPROVED** [review]
